name: php-code-style

on:
  push:
    paths:
      - "**.php"

jobs:
  php-code-style:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run code style fixer
        run: vendor/bin/pint

      - name: Commit code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: fix code style
